var doom = process.doom;

module.exports = {
    'gulp': doom.gulp,
    'run_sequence': require('run-sequence').use(doom.gulp),
    'fs': require('fs'),
    'browserify': require('browserify'),
    'del': require('del'),
    'transform': require('vinyl-transform'),
    'browser_sync': require('browser-sync'),
    'buffer': require('vinyl-buffer'),
    'source': require('vinyl-source-stream'),
    'imagemin': require('imagemin'),
    'argv': require('yargs').argv,
    'sassdoc': require('sassdoc'),
    'converter': require('sass-convert'),
    'vfs': require('vinyl-fs'),
    'replace': require('gulp-replace'),
    'order': require('gulp-order'),
    'concat': require('gulp-concat'),
    'size': require('gulp-size'),
    'streamify': require('gulp-streamify'),
    'uglify': require('gulp-uglifyjs'),
    'livereload': require('gulp-livereload'),
    'minify': require('gulp-minify-css'),
    'sass': require('gulp-sass'),
    'sourcemaps': require('gulp-sourcemaps'),
    'rename': require('gulp-rename'),
    'run': require('gulp-run'),
    'changed': require('gulp-changed'),
    'cache': require('gulp-cache'),
    'install': require('gulp-install'),
    'gulp_if': require('gulp-if'),
    'globbing': require('gulp-css-globbing'),
    'autoprefixer': require('gulp-autoprefixer'),
    'task_listing': require('gulp-task-listing'),
    'inline_css': require('gulp-inline-css'),
    'inject': require('gulp-inject'),
    'inject_style': require('gulp-style-inject'),
    'debug': require('gulp-debug')
};